### ISSUE TITLE
Command Line Arguments for PORT & HOST Not Prioritized

### ISSUE THREAD

**Issue by jimminy** [lukeed/sirv#104]
If your system environment has PORT or HOST defined, the command local arguments you pass will be ignored, due to how they are prioritized.

For PORT, this means if you happen to have another service relying on environment variables you're guaranteed to have a conflict, even when passing --port as a command line argument.

https://github.com/lukeed/sirv/blob/ede9189b6c586cd4697e0ffb16671515fdefecde/packages/sirv-cli/index.js#L81-L82

To resolve this issue, local arguments should be prioritized above environment.

```
opts.port = opts.port || PORT; 
let hostname = opts.host || HOST || 0.0.0.0;
```

**Comment by lukeed** [comment]
This is intentional. ENV is given priority.

**Comment by jimminy** [comment]
Seems like an odd intention, to ignore user intentions, creating conflict issues in a shared environment.

Real Example:
Having a Go service that is relying on an environment variable, PORT=5000.

Then starting sirv with sirv --port=3000, in an attempt to avoid port conflict, will still have sirv also attempt to listen on 5000, when the user intention is 3000.

See Thread: https://twitter.com/Jimminy/status/1378861264340840450
