### ISSUE TITLE
Content-Type charset=UTF-8 missing for text/html

### ISSUE THREAD

**Issue by rafrafek** [lukeed/sirv#106]
I'm running Svelte app with `sirv public --single --no-clear` and when I go to e.g. `http://localhost:5000/foo/` it is served with header:
`Content-Type: text/html`
It should be:
`Content-Type: text/html; charset=UTF-8`

Without `charset=UTF-8` in `Content-Type` header my web browser (Firefox) shows error in console that charset was not set.

I have set `<meta charset="utf-8">` in `<head>` of my `index.html` file which is served by Sirv, but it doesn't help.

**Comment by kotx** [comment]
I have this issue too, and Chromium logs it in the issues panel. However it's for all resources, not just for text/html.

**Comment by aleclarson** [comment]
+1 This interferes with hydration of a React app
