### ISSUE TITLE
error on filename with spaces.

### ISSUE THREAD

**Issue by chumager** [lukeed/sirv#107]
Hi, I recently changed from express.static to sirv, so far so good, but I realized a footer images were not displaying correctly.

After a lot of search I discover sirv may have a problem with filenames with spaces.

Of course for a image name it's not a problem to just change the name, but maybe for some other projects this could be a problem, for example a project where the designer upload directly the files.

Best regards.

**Comment by lukeed** [comment]
Hi there, I don't think this is true? We have tests for it: https://github.com/lukeed/sirv/commit/ede9189b6c586cd4697e0ffb16671515fdefecde
