### ISSUE TITLE
URL decoding in file names has been removed. Rollback it please.

### ISSUE THREAD

**Issue by NikolayMakhonin** [lukeed/sirv#110]
See this code lines:
https://github.com/lukeed/sirv/pull/64/files#r643652267
https://github.com/lukeed/sirv/pull/64/files#r643653381

Rollback please decodeURIComponent, because this issue is back: https://github.com/lukeed/sirv/pull/21

**Comment by lukeed** [comment]
Sorry, this is not true. You can share a reproduction (including sirv version) & together we can inspect what specifically is going on in your case, but on its own, sirv decodes all URLs.

Heading to bed now, but happy to walk thru an example/repro tomorrow :)
