### ISSUE TITLE
[Feature Request]: Directory listing

### ISSUE THREAD

**Issue by sidvishnoi** [lukeed/sirv#111]
[`vercel/serve`](https://github.com/vercel/serve/) has a nice feature where it displays a list of files in the directory if `index.html` doesn't exist, which is really helpful for navigation. Is this something that aligns with the goals of `sirv-cli`/`sirv`?

**Comment by lukeed** [comment]
Hey, probably not. That feature drove me nuts, personally. Immediately disqualified it as a production file server because it exposed everything inside, including possibly-sensitive files. If this were to exist here, it'd only be within `sirv-cli` and live behind its own CLI flag.

**Comment by sidvishnoi** [comment]
Makes sense. Though, sensitive files often have a common name (like `.env`), so they can't really be hidden on a static server.
I think keeping it behind a CLI flag is a good idea. Shall we keep this issue open for some time to see if it's something more people are interested in?

**Comment by lukeed** [comment]
Sensitive files as in _any_ file that should only be accessed via the appropriate Authentication & Authorization steps have taken place.

Yes, I'll keep this open to collect feedback/interest.
No, please don't send a PR until the time comes. Thank you though, but wouldn't want you to spend time on an unlikely-to-land feature. It's easy to implement, but it's a question of whether or not this _should_ exist & my current inclination is a "most likely it should not exist, but maybe under explicit opt-in"

**Comment by lukeed** [comment]
Closing as this hasn't been asked for by anyone since opening this issue (or before). If there are strong reasons to consider this in the future, we can discuss :+1:
