### ISSUE TITLE
Please allow setting the network and the local address simultaneously

### ISSUE THREAD

**Issue by tbenko73** [lukeed/sirv#123]
Please allow the use of Local: localhost alongside with custom Network: address.
If iI set a custom network address, ie:192.168.0.10 the Local address automatically changes to 0.0.0.0, and I cannot find a way to control the local address and the network address at the same time.
Is this possible somehow?

**Comment by lukeed** [comment]
As soon as something is accessible over the network, it's definitionally no longer "localhost" -- you can still type in `localhost` to visit the site, but it has to be opened up on 0.0.0.0 in order for other network members to locate your address.

The only way "around this' is to run two servers, where one is private and the other is exposed to the network...but that still forces you to be 0.0.0.0 anyway & then you have to deal with separate ports. Aka, this is no workaround, this is just how it works
