### ISSUE TITLE
Sirv cuts the file if its size increases

### ISSUE THREAD

**Issue by istudyatuni** [lukeed/sirv#131]
Hello! [Here](https://gist.github.com/istudyatuni/e95e815bc59380d0368b3d25779af52d) is the minimal reproduction for this. Briefly: after adding some code to the file and reloading page, the file is cropped to the old size.

`sirv, 2.0.2`

For example, I have

```js
// main.js
document.body.innerHTML = 'hi'

function longFunc() {
  let a = [[4, 5, 6], 6, 7, [0, 3]].flat().filter(e => e).map(e => e * 2).flat()
}

longFunc()
```

and include it

```html
<!-- index.html -->
<script type="module" src="main.js"></script>
```

if after first page load I change indentations in `main.js`

```js
document.body.innerHTML = 'hi'

function longFunc() {
  let a = [[4, 5, 6], 6, 7, [0, 3]]
    .flat()
    .filter(e => e)
    .map(e => e * 2)
    .flat()
}

longFunc()
```

and reload page, sirv will not return end of `main.js`:

```js
document.body.innerHTML = 'hi'

function longFunc() {
  let a = [[4, 5, 6], 6, 7, [0, 3]]
    .flat()
    .filter(e => e)
    .map(e => e * 2)
    .
```

*Sorry for my English*

**Comment by istudyatuni** [comment]
Hmm, I this it's because I didn't add `--dev`

**Comment by lukeed** [comment]
English is great 👍 And yes, this needs —dev to keep interacting with the filesystem. Without it, it’s serving from memory

**Comment by istudyatuni** [comment]
> English is great

I checked first half with DeepL :)
