### ISSUE TITLE
Add Changelog

### ISSUE THREAD

**Issue by thojanssens** [lukeed/sirv#134]
I have been updating my dependencies and my app just breaks.

Later to find out that the default port for this lib changed from 5000 to 8080 lol

As no changelog is present, there is no way for me to know how to fix my app with all the new changes?

**Comment by lukeed** [comment]
the semver convention means that major versions (1.x -> 2.0) will have breaking changes. 

Changelog is the [Releases](https://github.com/lukeed/sirv/releases) page, which is always updated. This is arguably the more common format for GitHub-hosted projects.

**Comment by thojanssens** [comment]
I didn't know that changelogs may be found inside the GitHub releases. Thank you 🤍
