### ISSUE TITLE
Question: reduce cache size?

### ISSUE THREAD

**Issue by PlopTheReal** [lukeed/sirv#143]
It looks like the cache holds all the stats of a file.
I suspect we could remove some of them to gain a bit such as 
```
dev
mode
nlink
uid
gid
rdev
ino
blocks
atimeMs
mtimeMs
ctimeMs
birthtimeMs
atime
ctime
birthtime
```
and keep 
```
size
mtime
```

**Comment by lukeed** [comment]
This is true for sirv's own usage, but `options.setHeaders` passes down the entire `fs.Stats` object for user to consume as desired. Changing that would be a breaking change

**Comment by PlopTheReal** [comment]
Ok thanks, I thought some might not be used anywhere but that's was just a suspicion..
