### ISSUE TITLE
[Feature Request] New option `base`. (Aka base path, public path, asssets URL root.)

### ISSUE THREAD

**Issue by brillout** [lukeed/sirv#148]
First off, thank you for building `sirv`, it's a really neat tool.

I've this use case where assets should be served from a different URL root, in my case `/assets/`. For example `/home/brillout/my-project/publicDir/logo.svg` should be served at `/assets/logo.svg` instead of `/logo.svg`.

The feature request is to be able set a new option `base` to the value `/assets/` making `sirv` serve all assets at `/assets/*`.

**Comment by lukeed** [comment]
Not sure how I didnt see this :/ sorry for delay

My reply is here: https://github.com/lukeed/sirv/pull/167#issuecomment-2532825131
