### ISSUE TITLE
When static file changed to longer during run

### ISSUE THREAD

**Issue by step135** [lukeed/sirv#151]
During the run of sirv, I am updating static files. But if the content is getting longer, the end is removed. It looks like that sirv wants to preserve the length of the string of files as it was when it started. I need to stop it and start it every time and it is enoying.

**Comment by lukeed** [comment]
It will if cache is enabled, yes, because it takes a snapshot at startup to avoid duplicate trips to file system. 

If you’re updating a file without restarting server then you have to use options.dev=true

**Comment by step135** [comment]
Thank you for explanation. I can't find anything about this behaviour and dev mode in documentation besides that it exists. I would advice to clarify it there for everyone. All the best!

**Comment by lukeed** [comment]
> Enable "dev" mode, which disables/skips caching. Instead, sirv will traverse the file system on every request.
