### ISSUE TITLE
Dev mode with cache control

### ISSUE THREAD

**Issue by axmad386** [lukeed/sirv#152]
I know in the docs that with dev = true it  will traverse the file system on every request. Is it possible to use dev mode but the http response still set the cache control? 
It will useful when we want to make public folder contain dynamic asset, we can add another asset to it, but when we access it browser will cache it.

**Comment by axmad386** [comment]
My workaround is to set `dev` to `true` and manage cache control via `setHeader` something like this
```ts
 sirv(public_path(),{
      dev:true,
      setHeaders: (res) => {
        res.setHeader("Cache-Control", "public,max-age=31536000,immutable");
      },
})
```
this will make sirv still serve the file dynamically but cache control is sent. So browser will cache the file

**Comment by lukeed** [comment]
dev mode won't apply Cache-Control ever, by design
Your solution is the appropriate way to approach the addition; **however** the `"public,max-age=31536000,immutable"` value used is a **recipe for disaster**, at least without some path filtering/matching
