### ISSUE TITLE
Is it possible to disable the fallback to index.html

### ISSUE THREAD

**Issue by tnwanna** [lukeed/sirv#160]
I'm trying to use this while having separate server routes that specifically serve the `index.html` file, but I can't seem to find any options to make this ignore that as a fallback. It seems to do so even when not in SPA mode and at the moment I just had to rename my `index.html` file to something else (which works, but ideally if I could avoid that step it would help)

**Comment by lukeed** [comment]
disable [`options.single`](https://github.com/lukeed/sirv/tree/main/packages/sirv#optssingle) and/or pass empty `[]` to [`options.extensions`](https://github.com/lukeed/sirv/tree/main/packages/sirv#optsextensions)
