### ISSUE TITLE
Add option to sirv-cli to not clear the console buffer

### ISSUE THREAD

**Issue by MaxMilton** [lukeed/sirv#17]
First off, awesome work on sirv. I use it basically every day and love the simplicity. So nice not to have to implement a native `http` server for each project to get the near native performance :heart: 

My typically use case is to add sirv (via `sirv-cli`) for testing production builds. e.g. in a package.json NPM script task which does a production build and then serves the build assets with sirv. Works great :+1: 

However, when sirv starts it clears the console buffer so I lose the ability to scroll back to see the build output. I find myself either stopping the build to see the output or running sirv in a separate console... but both these approaches are less than ideal. It would be useful to have a cli flag to disable clearing the console.

Not sure what the best option name would be, maybe something like `-n, --no-clear`?

**Comment by lukeed** [comment]
Hey, thanks! 🙇 

There was already a request & PR for this (https://github.com/lukeed/sirv/pull/12)... looks like I just haven't published a release since this 🙈

**Comment by MaxMilton** [comment]
Sweet! Sorry I didn't notice because it had already been merged :sweat_smile:

**Comment by lukeed** [comment]
No problem, I should have had it out already. There's something bugging me atm. Looking at it now, will have a new patch out later today~!

**Comment by MaxMilton** [comment]
I finally got the chance to try this out just now but it's not working as expected. Your `clear-console` package has problems on gnome-terminal on Linux.

I've also opened an issue on the  other package: https://github.com/lukeed/console-clear/issues/4

**Comment by lukeed** [comment]
Fixed in `console-clear@1.1.1`. New installs will pick this up~

Thanks!

**Comment by MaxMilton** [comment]
Works great, thank you :100:
