### ISSUE TITLE
Slow output for larger files

### ISSUE THREAD

**Issue by kazzkiq** [lukeed/sirv#19]
I tried to use sirv to deliver a moderately large JS file (~400kb) in dev environment, and noticed it had trouble handling it fast, even being static.

By opening it directly in browser, it took some seconds to load all its content. By fetching it via AJAX (my usage for this project) it also took the same time.

---

Edit:

[Here is a sample file](http://premioacolher.triggolabs.com/vendor.fde85bf6b4070f2d72bf.bundle.js), but I believe it may happen with any other format.

**Comment by lukeed** [comment]
Hey, this will be improved in the next major version of `sirv` – getting 1.0 out the door is near the top of my TODO list. Immediately after, 2.0 will be released with HTTP/2 support. This is when the problem will be fixed.

Unfortunately, in HTTP/1, the only way Node.js can send a file is by reading it & piping the contents to the response. Currently, `sirv` does this the most efficient way possible thru `fs.createReadStream`. It can _only_ be improved further if `sirv` held ***all*** your files' contents in memory, but this can quickly cause other problems 😕

**Comment by lukeed** [comment]
Completely forgot about `Range`/partial requests! 🤦‍♂️ All browsers will do this by default for large files (eg, videos, PDFs) so it will _seemingly_ speed up these large assets by sending them down in pieces.
