### ISSUE TITLE
URI encoding

### ISSUE THREAD

**Issue by Seb35** [lukeed/sirv#20]
When the requested file name contains a space or any other non-ASCII character, sirv searches the file named with the percent-encoded name, e.g. if `/my file.txt` is requested, then sirv searches a file named `my%20file.txt`, which is not what is expected in the file system.

This occurs both in dev mode and in normal mode.

It can be fixed by adding `uri = decodeURI(uri)` or `uri = decodeURIComponent(uri)` -- I’m not sure what variant should be used here.

**Comment by lukeed** [comment]
Hey, this is already to be fixed in next version. I've made it so that `@poloa/url` handles this (correctly) for all packages
