### ISSUE TITLE
Allow `setHeaders` while using dev mode

### ISSUE THREAD

**Issue by kristoferbaxter** [lukeed/sirv#22]
I have a use-case where even in dev mode I need specific headers to be set, as a result I'm using prod mode but restarting node when FS changes are detected.

Would adding `setHeaders` into dev mode be a huge burden?

**Comment by lukeed** [comment]
Not a burden at all~! Will add it now, makes sense to have.

**Comment by kristoferbaxter** [comment]
Thanks!
