### ISSUE TITLE
Unexpected path in SPA mode 

### ISSUE THREAD

**Issue by si3nloong** [lukeed/sirv#25]
<img width="685" alt="Screenshot 2019-05-07 at 12 43 41 PM" src="https://user-images.githubusercontent.com/28108597/57272319-d2dbd000-70c5-11e9-89f0-8a4892a82954.png">

i pass in the --single option but it doesn't work what i expected, the full path should be global.css instead of /r1/r2/r3/global.css

**Comment by lukeed** [comment]
This doesn't look like a sirv problem. What does your markup look like?

Is it `href=global.css` or `href=/global.css`? The latter is correct. The first will produce the error you are seeing.

**Comment by si3nloong** [comment]
@lukeed thanks, it work
