### ISSUE TITLE
Documentation: --dev option not mentioned in README.

### ISSUE THREAD

**Issue by owaisalhashimi** [lukeed/sirv#27]
The --dev option is not mentioned in the README (GH and NPM sites), and only shows up when doing --help in CLI. Please document the --dev option for completeness.

**Comment by paulocoghi** [comment]
I made a [PR](https://github.com/lukeed/sirv/pull/28) ( https://github.com/lukeed/sirv/pull/28 ) with the mention. Thanks for the note!

**Comment by lukeed** [comment]
Thanks for pointing that out 🙌

**Comment by owaisalhashimi** [comment]
@paulocoghi @lukeed  Welcome. Thanks for sorting.
