### ISSUE TITLE
Help with sirv in sapper apps

### ISSUE THREAD

**Issue by vladejs** [lukeed/sirv#34]
Hi, I just audited my app with Lighthouse and it says that my static resources needs an efficient caching policy. For example, by setting the header max-Age TTL header.

Effectively, I'm seeing all my assets (images, fonts) with `no-cache` header set.

Is there a way I need to configure `sirv` Middleware to fix this?

**Comment by lukeed** [comment]
Hey, yes you can

See [`maxAge`](https://github.com/lukeed/sirv/tree/master/packages/sirv#optsmaxage) as well as the `immutable` and `etag` options.

If you want to do something more custom (eg, respond to specific paths, like setting no-cache on service worker) then you will also want to use `setHeader` function

Hope that helps. You can do anything with those pieces
