### ISSUE TITLE
Any plan to have live reload feature?

### ISSUE THREAD

**Issue by anonimusprogramus** [lukeed/sirv#37]
Like, run from cli.

**Comment by lukeed** [comment]
Hey, no there isn't – not for `sirv` at least! 

I've been sitting on a semi-complete HMR module, which is totally separate from sirv(-cli). That one is meant to be the `webpack-dev-server` equivalent, whereas sirv is (and always was) meant to be the production-like server.

I'll try to remember to follow up here when that's released. But, for now, the plan is to release a `sirv@1.0.0` once that dev module is available too.
