### ISSUE TITLE
Accept Ranges: bytes

### ISSUE THREAD

**Issue by subz390** [lukeed/sirv#40]
How easy would it be to add support for video range requests?  If it's non-trivial then not to worry, thought I'd ask.  
I am writing something that plays videos in HTML5 and noticed that `url#t=[start_time][,end_time]` wasn't working, and then realised that sirv didn't have `Accept Ranges: bytes` for the video content request although it was serving the file ok.  Would be nice to have the feature but if it's not within the scope of this project then fair enough.  Thank you.

**Comment by paulocoghi** [comment]
It seems that Lukeed already implemented it. (https://github.com/lukeed/sirv/blob/master/packages/sirv/index.js#L65)

**Comment by subz390** [comment]
Thanks @paulocoghi I'll have a dig around tomorrow to find out why this isn't working for me with sirv but is with Live Server.

**Comment by lukeed** [comment]
Hey, make sure you're on the latest. You can send a file or reproduction if it's not working

**Comment by subz390** [comment]
version check
```bash
λ yarn list --pattern sirv
yarn list v1.17.3
├─ sirv-cli@0.4.4
└─ sirv@0.4.2
```
So this is one step away from me having to build a repo for you.  However this test is just an mp4 file in the public folder and a couple of links to it.
```html
<a href="http://localhost:5000/test.mp4#t=01:00">http://localhost:5000/test.mp4#t=01:00</a>
<a href="http://localhost:5502/test.mp4#t=01:00">http://localhost:5502/test.mp4#t=01:00</a>
```
Run up sirv from a script in `package.json`, and [Live server](https://marketplace.visualstudio.com/items?itemName=ritwickdey.LiveServer)
```json
"scripts": {
  "sirv:dev": "sirv public --single --dev",
}
```
Then click on the links and observe what happens, here's the results.
![liveserver](https://user-images.githubusercontent.com/11546815/64235813-0b16e200-cef1-11e9-8703-48574f2adb04.png)
![sirv](https://user-images.githubusercontent.com/11546815/64235815-0baf7880-cef1-11e9-9e20-0ddc95dd5da8.png)

What I don't understand is why the browser isn't sending request headers to sirv when requesting the video file, but it's sending headers for other files like stylesheet, script, websocket, img.  Doesn't make any sense.
I mean are you having any issues loading videos? is it just me?  I'll be happy to send a repo next if you need.

**Comment by subz390** [comment]
update: done some more investigating and found that embedding in `<video></video>` tags works as expected with content ranges on both Chrome and Firefox.  However it's only Chrome that opens the video at a specified location when directly linking to the video ie not embedded, where as Firefox for some strange reason doesn't.

**Comment by paulocoghi** [comment]
Firefox may expect the `range` header previously on the first request for the direct access case. On the [specification](https://developer.mozilla.org/en-US/docs/Web/HTTP/Range_requests) we see that it's not required to the web server to do so, but in this specific case of Firefox, it might be expect it.

**Comment by paulocoghi** [comment]
In other words, despite the `Accept-Ranges` header isn't required before sending data, in some cases the browser may understand that the web server doesn't support ranges when this header isn't present.

For this issue, Firefox may be understanding that it doesn't support ranges on direct access, because it isn't even trying to test a range request.

I believe that, to solve this, sirv would have to always send the `Accept-Ranges` header on the first response, to ensure to the browser that it supports it, but this could potentially reduce the performance.

**Comment by subz390** [comment]
Ok so here's a summary:  servers and browsers aren't required to do anything with range requests, but when they do then either side can do something about it.  
So due to this policy when requesting a video directly in the browser window one can expect inconsistent results.  
However range requests should work as expected in a typical use case, for example when embedding a video in an [HTML Video element ](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/video).  I've tested Sirv with Chrome and Firefox and in both cases everything works as expected.  I'm happy to leave it there.

Here's the RFC for reference;
>    An origin server that supports byte-range requests for a given target
   resource **MAY** send
     `Accept-Ranges: bytes`
   to indicate what range units are supported.  A client **MAY** generate
   range requests without having received this header field for the
   resource involved.
[RFC 7233 HTTP/1.1 Range Requests](https://tools.ietf.org/html/rfc7233)
