### ISSUE TITLE
sirv README still says polka returns a Promise from listen()

### ISSUE THREAD

**Issue by rdmurphy** [lukeed/sirv#42]
Hello! 👋 

Was just trying to spin up a quick demo based on the code samples in `sirv` and quickly hit an error with `polka().listen()`. I can see in `polka` where `listen()` no longer returns a Promise, but this change wasn't reflected here. Just wanted to give you a heads up!

Thank you!

**Comment by lukeed** [comment]
Hey – oops, thanks!

I have to touch all the `sirv` documentation before next stable release, but I fixed it in `next` branch for now.

Thanks!
