### ISSUE TITLE
Feature: Use with folder partitioning

### ISSUE THREAD

**Issue by pke** [lukeed/sirv#47]
I wonder if I could use this static file middleware for my situation.
I need to store file uploads in a folder called `blobs` and since I expect a lot of files they should not be stored in the same directory. Instead I want to partition the `blobs` directory with 3 subdirectories based on the files content hash: 

`blobs/hash{0,3}/hash{3,6}/hash{6,9}/hash.ext`

requests the like `/hash` should then fetch the file from this partitioned directory.
Also after creating the file I'd like to immediately update the `sirv` cache with this new file. Precompressing the file to .gz and brotli would be nice too.

Any ideas if that could be accomplished?

**Comment by lukeed** [comment]
Hey again,

I'm fairly certain we spoke about this in other channels. The TLDR was that sirv is just meant to traverse a file structure for exact matches.

If you need/want custom routing logic, you have to employ a routing layer in front of sirv. 
With this, what you're asking for is certainly possible, but _very_ specific to your application and so it's not something sirv or sirv-cli will do for you.

But thank you for the idea!

**Comment by pke** [comment]
Sure, no problem ;)
I think I will not use a node app for static file serving anyway but a reverse proxy like nginx or caddy.

**Comment by lukeed** [comment]
Sounds good :) If you have/are willing to put the infrastructure in place, it's a better solution anyway.

Good luck~!

**Comment by pke** [comment]
Yeah, I really miss some nginx + node tutorials where they explain that serving static files with node is maybe not a good idea.
Maybe I'll write one myself when I am done.

**Comment by lukeed** [comment]
Right; Node is not the best solution for file-serving. Basically `sirv` only exists so that people who are trying to do everything inside Node.js can still have a decent option.

Personally I use sirv for development and running production-like servers locally.
