### ISSUE TITLE
Update FILES when reading from disk?

### ISSUE THREAD

**Issue by developit** [lukeed/sirv#5]
I might be missing something, but would it make sense to update the cached entry in FILES when going to disk in the request handler?

**Comment by lukeed** [comment]
Update what portion of the entry?

**Comment by lukeed** [comment]
Maybe I'm misreading the question on second go-round, but the `FILES` cache is updated [here](https://github.com/lukeed/sirv/blob/master/packages/sirv/index.js#L55) as a result of `tiny-glob`'s output. 

We're expanding the glob pattern initially to retrieve the `fs.stats` objects & save the absolute paths. Then passing the stats for writing headers & passing the filepath into `fs.createReadStream` which is piped into the outgoing response.

Initially I thought you were asking about updating `FILES` during the pipe from `fs` into `res`. If that _is_ the question, then what needs to be updated?

**Comment by lukeed** [comment]
Spoke with Jason offline; we're okay to close this 😄

**Comment by lukeed** [comment]
Version `0.2.0` now includes a `--dev` flag (and option) which bypasses the files cache entirely. Indicated by the name, not meant for production~!
