### ISSUE TITLE
Is there a good way to transform responses?

### ISSUE THREAD

**Issue by evanleck** [lukeed/sirv#52]
This may be outside the scope of sirv, but I'd like to modify the response body on the way to the client. In this case, I have a mostly static JavaScript file that I'm bundling with Rollup but I'd like to do some simple string substitution on the final response to include some request-specific data.

I understand that sirv pipes a readable stream to the response but I can't for the life of me figure out how to modify the contents of the stream... any help would be much appreciated.

Thanks!

**Comment by lukeed** [comment]
Hey, no, sorry

Sirv is just a _static_ file server. It'll pipe what's there. 

You'd need a dynamic server of some kind that applies the logic & transformation you want. You could probably stick a proxy server in front of wherever `sirv` is running, but that's probably too many dominoes at play for such a small thing.

Dunno what kind of transformation you're after, but I'd start by looking at [transformation streams](https://nodejs.org/api/stream.html#stream_class_stream_transform) if you haven't already.

Hope that helps!

**Comment by evanleck** [comment]
Totally makes sense, I appreciate you pointing me to those docs though! Thanks!
