### ISSUE TITLE
totalist/sync and list take a pre argument but we do not expose it as an option 

### ISSUE THREAD

**Issue by goliatone** [lukeed/sirv#59]
The `list` function takes three arguments:
* dir
* callback
* prefix

Current implementation in both master and next do not provide an option to pass the prefix to the `list` function.

**Comment by lukeed** [comment]
That argument from totalist is meant for tracking its internal recursion on the directory traversal only. 

When using totalist, it's not meant to be defined manually, plus there'd be not purpose in doing it.

**Comment by goliatone** [comment]
@lukeed >plus there'd be not purpose in doing it.

I have multiple mounted apps, I want to serve static files from a public folder found on each subapp directory. 

So, I want to be able to serve:

* http://localhost/admin/css/style.css
* http://localhost/dashboard/css/style.css

As it is currently, I can register two public sirv middlewares. And both of those requests will resolve. However since the paths are resolved without the mounted app segment in the URL both files and `FILES` is global then both are stored with the same `uri`. 

* http://localhost/admin/css/style.css: `FILES[/css/style.css]`
* http://localhost/dashboard/css/style.css: `FILES[/css/style.css]`

```
.
├── server
├── admin
│   ├── public
│   ├── routes
│   └── views
├── dashboard
│   ├── public
│   ├── routes
│   └── views
```
