### ISSUE TITLE
Option to auto generate self-signed TLS certificates

### ISSUE THREAD

**Issue by pl12133** [lukeed/sirv#60]
The `next` branch provides TLS support which is great, but we need to specify our own key and certificate file which can be cumbersome for development. Would there be any interest in adding [`pem`](https://www.npmjs.com/package/pem) for auto generating certificates? Maybe behind a `--self-signed` option.

**Comment by lukeed** [comment]
Hey there,

Thanks for the suggestion & opening a ticket first :)

> Would there be any interest in adding `pem` for auto generating certificates? 

No, this is definitely fall out of scope for the package. This, at best, would only be used once – ever. At worst, you'd be accidentally creating new self-signed certificates (across deployments, for example), which would cause far more trouble in the long run.

I'd much rather include instructions using `pem` or `open-ssl` for generating certificates. While it's not as "nice" – it helps prevent users from shooting themselves in the foot

**Comment by pl12133** [comment]
Thanks for the fast answer! I understand that could be a foot gun, so I see why you wouldn't want to support that option. I found myself testing production builds from `preact-cli` on my development machine pretty often which was what motivated me to think of this. Like you said it is easy enough to use a certificate generator alongside `sirv-cli` to get self-signed certificates going anyway.

If anyone else wants to do this, here is my example:

```js
const fs = require('fs');
const pem = require('pem');
const shell = require('shelljs');

const keyFile = 'key.pem';
const certFile = 'cert.pem';

let promise;
if (!fs.existsSync(keyFile) || !fs.existsSync(certFile)) {
  promise = new Promise((resolve, reject) => {
    pem.createCertificate({ days: 1, selfSigned: true }, function (err, keys) {
      if (err) { return reject(err); }

      fs.writeFileSync(keyFile, keys.serviceKey);
      fs.writeFileSync(certFile, keys.certificate);
      resolve();
    });
  });
} else {
  promise = Promise.resolve();
}

promise.then(() => {
  shell.exec(`npx sirv . --host 0.0.0.0 --cors --single --http2 --key ${keyFile} --cert ${certFile}`);
});
```

**Comment by lukeed** [comment]
Thanks for posting a recipe :)
