### ISSUE TITLE
https & http at the same time when `--single`?

### ISSUE THREAD

**Issue by longrunningprocess** [lukeed/sirv#66]
THANK YOU first and foremost for the latest update, I've been banging my head against the wall trying to get certs working locally for https and thought I needed to use `http-server` or `servor` or something but I just noticed your release yesterday and low and behold it's running https now, THANK YOU!!!

So, should `sirv --single` respond to `http` **AND** `https` simultaneously?  My local one is not responding to `http` calls when I spin it up like this:
```
sirv dist --dev --host 0.0.0.0 --single --http2 --key key.pem --cert cert.pem
```

I can put multiple commands in place to address it but would appreciate it responding to both consistently.

browser refresh for https://localhost:5000/home (`--single` is working)
![image](https://user-images.githubusercontent.com/4412848/85067336-8561db80-b17e-11ea-9628-1ef643ec54fd.png)

browser refresh for http://localhost:5000/home (`--single` is **NOT** working?)
![image](https://user-images.githubusercontent.com/4412848/85067426-a9252180-b17e-11ea-93f8-820d7b8cc19e.png)

**Comment by lukeed** [comment]
Thank you :) I'm glad it's helpful

No, it should not respond to `http` when the `https` protocol is in use. This is true of all Node.js servers. 
The change in protocol makes for a different address entirely. If you want to listen over both protocols, you have to setup two servers.

Front end proxies (eg, NGINX) will accept traffic on multiple ports and forward that traffic to a single destination.
In `sirv`'s case (and most any Node.js app), our server _is_ the destination. You could setup your own Node.js proxy that listens for both protocols and forwards the traffic, but that's not something `sirv` provides or intends to

Hope that helps~!

**Comment by longrunningprocess** [comment]
for my own future reference, here's a way to achieve what I wanted:

### package.json
```
    "serve": "run-p -l serve:http serve:https",
    "serve:http": "sirv dist --dev --host 0.0.0.0 --port 8080 --single",
    "serve:https": "sirv dist --dev --host 0.0.0.0 --port 8443 --single --http2 --key key.pem --cert cert.pem"
```

### output
![image](https://user-images.githubusercontent.com/4412848/85071099-f906e700-b184-11ea-9715-6b9d6c055c72.png)
