### ISSUE TITLE
Unable to serve sub directory in windows

### ISSUE THREAD

**Issue by antonheryanto** [lukeed/sirv#7]
current version only able to serve file on root directory as the file separator in windows different with req.pathname

expected FILES mapping
```{ "/img/logo.png": "public\\img\\logo.png'}```
actually
```{ "/img\\logo.png": "public\\img\\logo.png'}```

**Comment by lukeed** [comment]
Oh whoops, nevermind :) I'm on my phone, I'll review the PR within the hour. Thanks!!

**Comment by andreujuanc** [comment]
Thanks @antonheryanto
