### ISSUE TITLE
Can't access server over local network

### ISSUE THREAD

**Issue by mhkeller** [lukeed/sirv#70]
When I launch a server via sirv-cli, I can't access that server from another computer on the local network. I put together [this reproduction repo](https://github.com/mhkeller/test-server) so you can see how this issue doesn't occur with two other libraries. 

I tried it with `-c` and `--cors` but that didn't fix it. If I manually set the local ip address via `-H` that does fix it.

**Comment by lukeed** [comment]
Hey,

You have to specify `--host` if you want it exposed to the network. If you leave it like that, it's the same as `--host 0.0.0.0` but you can customize it if desired. The set of 0s will expose it to your network (address shown in console) so that you can do mobile testing, for example.

By default, it's purely a localhost server (aka, private) since that's all a server needs -- and it's a better default to have, especially when coffeeshops/shared spaces were a thing.

**Comment by mhkeller** [comment]
Haha I vaguely remember coffeeshops. Got it. I think maybe adding that you can expose it to the local network by setting `--host 0.0.0.0` would be a useful addition to the readme – I for sure wouldn't have figured that out. I thought trying the cors option was going to fix it (after fiddling with my local apache config for an ill-advised hour 🤦‍♂️). That for sure makes sense that this is the more secure default.

**Comment by mhkeller** [comment]
Maybe adding a line to the default console output could be helpful for people who may be coming from svelte template land and might not know to look at sirv. Something like this perhaps?

```
Your application is ready!~

- Local: http://0.0.0.0:8080

Hint: Set `--host 0.0.0.0` to expose on the local network
```

**Comment by mhkeller** [comment]
I'd be happy to do a PR to help take the load off!

**Comment by lukeed** [comment]
Ah ya, if you're up for a PR can you add a section to the CLI's readme, above the HTTP/2 section?

I don't think it should live inside the CLI text output. I don't know if I consider sirv-cli primarily a dev tool. But adding it as a [an example](https://github.com/lukeed/sirv/blob/master/packages/sirv-cli/bin.js#L10) in the helptext sounds like a good addition!

The svelte templates have updated a lotttt wrt `sirv-cli` flags. I think it used to be in there as a default, but rolled back for security concerns.

**Comment by Rich-Harris** [comment]
FWIW I think @mhkeller makes a good point about people consuming sirv indirectly — it's not clear from this...

![sirv-cli screenshot](https://github.com/lukeed/sirv/raw/master/sirv-cli.png)

...that there's a package called 'sirv' involved, so people might not know where to look. Given that similar packages *do* expose the server to the network, I can definitely see how it could be a source of confusion. Perhaps as an alternative/addition to this...

```
Your application is ready!~

- Local: http://localhost:8080
- Network: use `--host` to expose to the network
```

...it'd be worth pointing people to the project directly:

```
Your application is ready!~

- Local: http://localhost:8080

Visit https://github.com/lukeed/sirv for more info
```

**Comment by lukeed** [comment]
I like how both of you interpret my `~!` 😆 

Yeah, I've been thinking about it and I think it would be better to show a `--host` message in the absence of the flag.
@mhkeller If you open that PR for readme and/or the hint, I'll fiddle with the styling.

Thanks!

**Comment by mhkeller** [comment]
Haha woops that's my typo transposing the `~!`! 

So to recap, @lukeed you're preferring this proposal?

```
Your application is ready~! 🚀

- Local: http://localhost:8080
- Network: use `--host` to expose to the network
```

**Comment by lukeed** [comment]
Yup, some variant of that should do the trick. Don't need my name showing up front & center
