### ISSUE TITLE
Question: is there a way to specify the assets access path?

### ISSUE THREAD

**Issue by hydroper** [lukeed/sirv#78]
For example: `sirv('../assets', { accessPath: 'assets' })`. This should allow requests to Express.js to access the '../assets' directory using 'assets'. As is, without this option, I get 404.

**Comment by lukeed** [comment]
Sirv is a middleware, not a router. You use Express/Polka to setup the router.

```js
app()
  .use('/assets', sirv('/path/to/assets'))
  // ...
```

Hope that helps~
