### ISSUE TITLE
Can't override *all* headers via `setHeaders`?

### ISSUE THREAD

**Issue by staydecent** [lukeed/sirv#79]
I'm trying to disable Cache-Control for a single file, but default to the maxAge provided for all other files.

```javascript
const assets = sirv('public', {
  maxAge: !DEV ? 31536000 : 0, // 1Y
  immutable: false,
  setHeaders: (res, pathname, stats) => {
    if (pathname === '/') { // only want to disable cache for index.html
      res.setHeader('Cache-Control', 'public,max-age=0')
      console.log('CACHE?')
    }
  }
})
```

The `setHeaders` function is called and there are no errors, but the Cache-Control is never overridden for index.html. I inspected the source code, and it looks like headers are actually passed in to `send` as a plain JS object: https://github.com/lukeed/sirv/blob/master/packages/sirv/index.js#L166

And the only header value copied from the ServerResponse is `content-type`: https://github.com/lukeed/sirv/blob/master/packages/sirv/index.js#L61

When `writeHead` is called, precedence is giving to the headers object passed in: https://nodejs.org/api/http.html#http_response_writehead_statuscode_statusmessage_headers

Anyway, that is my understanding of the code. I'm wondering if it makes sense to alter the internal code to allow `setHeaders` to explicitly override a header, or if we should update the documentation to mention that the following headers will have precedence internally:

```javascript
{
  'Content-Length': 3374,
  'Content-Type': 'text/html',
  'Last-Modified': 'Wed, 12 Aug 2020 19:38:14 GMT',
  'Cache-Control': 'public,max-age=31536000'
}
```

Appreciate any insight, corrections, etc. for this!

**Comment by lukeed** [comment]
Hey, thanks for this! You were right! 
The only correction is that `content-length` should not ever be modified – nor any range-based headers

**Comment by lukeed** [comment]
Can you give the linked commit a try locally and verify for me that it solves your case?

This was a regression from the `0.x` versions, but it looks correct to me now.
Will publish once you've given a thumbs up :)

**Comment by staydecent** [comment]
@lukeed Works perfectly! Appreciate the quick response/turn-around on this 🙌

**Comment by lukeed** [comment]
Great, thanks! Appreciate the detailed report.
