### ISSUE TITLE
Way to set ignores flag as false from sirv-cli

### ISSUE THREAD

**Issue by hyeonseok** [lukeed/sirv#80]
It looks only a string or `true` can be set from sirv-cli. Is there a way to set it as false from sirv-cli command?

I'm using sirv in Svelte and want that it does not ignore url with extensions with --single option.

**Comment by lukeed** [comment]
Hey, 

For most CLIs, `--no-[name]` generally works :) 
That's the answer in this case too: `--no-ignores`

Hope that helps!
