### ISSUE TITLE
Question: re: path to assets (again)

### ISSUE THREAD

**Issue by tleylan** [lukeed/sirv#83]
Hi. I reviewed the closed items and noticed similar questions but... I would like to move the assets folder out from under public as some some companies/projects have shared assets folders. I'm using a Svelte SPA app and whatever sirv install is used with it. My command line in the most simple form is sirv public -s. Is there any command line option to point to another folder to be the root for assets? I don't expressly set up a Node-based server so I don't believe I have that option available to modify.

Thanks.

**Comment by lukeed** [comment]
Hey, `sirv-cli` itself only serves one directory. It doesn't have to be "public" of course, but the CLI itself only maps 1 directory to the file server it provides.

If you want to, say, have `static/assets` and `public/assets` both map to the `/assets` URL prefix, you can do that through `sirv` programmatically. Something like:

```js
const assets1 = sirv('public/assets');
const assets2 = sirv('static/assets');

polka()
  .use('/assets', assets1, assets2)
  // ...
```

You need something like a Polka to control that take on that extra proxy/routing step. The only "routing" `sirv` itself does is a 1:1 lookup between the incoming URL and the file structure. A Polka-type tells `sirv`: "only pay attention to these _or these portions of_ URLs"

Hope that helps!
