### ISSUE TITLE
Add --quiet-logs option or something like?

### ISSUE THREAD

**Issue by syabro** [lukeed/sirv#85]
It would be great for me if logs will be disabled too on quiet mode but banner on start with opened port should be shown (Default port is occupied often, so I want to know which is serverd by sirv.

So just omit this:

```
  [19:05:43] 200 ─ 3.77ms ─ /
  [19:05:43] 404 ─ 0.17ms ─ /tailwind.css
  [19:05:43] 200 ─ 1.04ms ─ /app.js
  [19:05:43] 200 ─ 8.00ms ─ /app.css
  [19:05:43] 404 ─ 0.11ms ─ /img/logo.svg
```

**Comment by lukeed** [comment]
OK. This isn't the first time this has come up, so might as well. How about `--quiet logs` or `--quiet requests`?

**Comment by lukeed** [comment]
Or `--no-logs`

**Comment by syabro** [comment]
`--no-logs` looks good

**Comment by lukeed** [comment]
Added `--no-logs` to `sirv-cli@1.0.8` – thanks!
