### ISSUE TITLE
Option to serve with path

### ISSUE THREAD

**Issue by cotyhamilton** [lukeed/sirv#87]
Would be cool to have an option to serve under a path other than root.

For example

`sirv --single --dev --basepath MyApp `

Which would serve it at localhost:5000/MyApp

**Comment by lukeed** [comment]
The only routing sirv will do is 1:1 mapping of requests to file structure. If you need something more, you should stand up a Polka or any proxy server.

In this case, you could skip all that and create assets inside `/public/MyApp` and then `sirv public`

Hope that helps

**Comment by cotyhamilton** [comment]
Alright, thank you for the suggestion
