### ISSUE TITLE
Undefined VoidFunction reference in sirv.d.ts

### ISSUE THREAD

**Issue by benmccann** [lukeed/sirv#89]
https://github.com/lukeed/sirv/blob/2dec57c2407501f76775d3a580ec144ed4264b71/packages/sirv/sirv.d.ts#L6

```
sirv@1.0.7/node_modules/sirv/sirv.d.ts:6:28 - error TS2304: Cannot find name 'VoidFunction'.
6  export type NextHandler = VoidFunction | Promise<void>;
```

**Comment by lukeed** [comment]
Thanks! TIL that `VoidFunction` is defined in `lib.dom.ts` .. i thought it was a TS global.
