### ISSUE TITLE
Should use Cache-Control: no-cache instead of no-store when etag option is true

### ISSUE THREAD

**Issue by yyx990803** [lukeed/sirv#90]
When using

```js
sirv(dir, { dev: true, etag: true })
```

The etag will be effectively useless because in dev mode the `Cache-Control` header is set to `no-store`, which causes Chrome to not include `If-None-Match` when requesting the file again.

I would suggest using `no-cache` instead when `etag` is enabled so that we can leverage 304 even in dev.

**Comment by lukeed** [comment]
Thanks Evan :) Overlooked that.

**Comment by lukeed** [comment]
Available in `1.0.10

**Comment by yyx990803** [comment]
Thanks that was fast!

**Comment by lukeed** [comment]
You gave a full explanation – and it was easy 😉
