### ISSUE TITLE
FYI: sirvy, an ES module based, content-modifying version

### ISSUE THREAD

**Issue by akauppi** [lukeed/sirv#93]
Hi @lukeed 

I needed a way to inject two access strings and (long story short) ended up having two, ES module based variants of sirv[-cli] 1.0.10.

It dawned to me during the work how un-sirv editing content on the fly was, but it works and this allows me to use sirv-y in the future. The need for the injection comes from Firebase (Google), which has two semi-secret access strings in HTML. They are not truly secret, but Google recommends not placing them in the source code.

Since I was making a web component, I wanted the use sample to be ultra simple. Which it now still is. :)

Cheers for the code! If you intend to make ES module versions of it, some of the changes I made can help.

https://github.com/akauppi/aside-keys/tree/master/tools

**Comment by lukeed** [comment]
Hey, cool :) Glad you were able to do/find what you needed. Thanks for maintaining original references, too

To address some of the questions/comments I saw you had:

https://github.com/akauppi/aside-keys/blob/master/tools/sirvy/index.js#L36

Yes, Array.p.some is slow – see [here](https://github.com/lukeed/arr/blob/master/benchmarks/results/node-12.md#some)

https://github.com/akauppi/aside-keys/blob/master/tools/sirvy/index.js#L188

Use of `next` is to maintain the middleware signature for Polka/Express-like servers.

https://github.com/akauppi/aside-keys/blob/master/tools/sirvy-cli/index.js#L26

No, `console-clear` is just a dictionary with cross-platform terminal sequences.
The argument parsing is done by [`mri`](https://github.com/lukeed/mri) (via [`sade`](https://github.com/lukeed/sade)). It's a convention in JS argv parsers (whether tools expose it or not is a different story), to always listen for `--no-{flag}` variants.

Closing this as it's not an issue, but I hope those answers were a bit helpful.
Thanks!
