### ISSUE TITLE
Use mime lite

### ISSUE THREAD

**Issue by richajak** [lukeed/sirv#96]
The author of "mime", "broofa" also provides "lite" version of this module that omits vendor-specific (*/vnd.*) and experimental (*/x-*) types. I have checked the difference, the lite version will load "types/standard.js" 10kb, while the normal version will load both "types/standard.js" 10kb and "types/other" 26kb.

`const mime = require('mime/lite');`

**Comment by lukeed** [comment]
https://github.com/lukeed/sirv/blob/master/packages/sirv/index.js#L5

**Comment by richajak** [comment]
thanks, didn't realize that. I saw that the command `npm list --depth 1` returned the whole mime package. The 'node_modules' generated by npm simply grabbed the whole 'mime' package. I guess it's the problem with npm.

**Comment by lukeed** [comment]
No, it's correct. The package is `mime` -- `mime/lite` is what's known as a submodule or a non-main entry/export
