### ISSUE TITLE
cache cannot be stale

### ISSUE THREAD

**Issue by hokamc** [lukeed/sirv#99]
After building svelte app, i try to serve site with sirv. 

`sirv public --quiet --etag --maxage 31536000 --immutable --gzip`

However, I am facing a problem that cache cannot be stale after I change svelte code and rebuild again. p.s. I test it in a firefox.

In my observation, etag has been updated and only bundle.js has the problem of cache.

**Comment by hokamc** [comment]
just remove immutable 
ref: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control

**Comment by lukeed** [comment]
Yes, immutable directive means that the contents at a given URL will _never_ change. It should only be used in production, with filenames containing a content-based hash in the filename.
